[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x"]

[phases.install]
cmds = ["pnpm i --frozen-lockfile --config.engine-strict=false"]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run start"
