name: Reset Demo Account
on:
  schedule:
    - cron: '*/30 * * * *' # Every 30 minutes
  workflow_dispatch: # Manual trigger

jobs:
  reset-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Reset demo account data
        run: |
          curl -X POST https://devhub.party/api/ingest \
            -H "Content-Type: application/json" \
            -d '{"task": "seed_demo", "token": "${{ secrets.INGEST_TOKEN }}"}'
