name: 'Tests: Unit'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.1-noble
      options: --user 1001

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4.2.0
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: 22.x
          cache: 'pnpm'

      - name: Verify Playwright versions match
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').devDependencies.playwright.replace('^', '')")
          CONTAINER_VERSION="1.56.1"
          if [ "$PACKAGE_VERSION" != "$CONTAINER_VERSION" ]; then
            echo "::error::Playwright versions don't match!"
            echo "::error::Package.json: $PACKAGE_VERSION"
            echo "::error::Container: $CONTAINER_VERSION"
            exit 1
          fi

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: pnpm run test:ci
        env:
          PUBLIC_FATHOM_ID: test_fathom_id
          PUBLIC_FATHOM_URL: https://test.example.com
